name: Build documentation

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

jobs:
    build-docs:
        name: Build on python ${{ matrix.python-version }} and ${{ matrix.os }}
        if: "!contains(github.event.head_commit.message, '[ci skip]')"
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                python-version: ["3.x"]
                os: [ubuntu-latest]
        steps:
            - uses: actions/checkout@v2
              with:
                submodules: true
            - name: Use python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install Sphinx
              run: pip install Sphinx
            - name: Install gettext
              run: sudo apt-get install -y gettext
            - name: Build the documentation
              run: make html SPHINXOPTS='-n -W -a'
            - name: Build the documentation and show all errors
              if: ${{ failure() }}
              # This mode will not exit on the first error and will display all of them
              run: make html SPHINXOPTS='-n -a'
